/** Stored in brush_tips IndexedDB store — shared across presets and documents. */
export interface StoredBrushTip {
  id: string;
  pixels: Uint8Array;
  width: number;
  height: number;
}

import type { ShapeDynamics, TransferDynamics, ScatterSettings, DualBrushSettings, TextureSettings, WetMediaSettings } from "./hooks/useBrushSettings";

/** Pen-pressure size dynamics shared by all wet media presets. */
const WET_MEDIA_SHAPE_DYNAMICS: ShapeDynamics = {
  size: { jitter: 0, control: 1, minimum: 0.2 },
  angle: { jitter: 0, control: 0, minimum: 0 },
  roundness: { jitter: 0, control: 0, minimum: 0 },
};

/** Stored in brush_presets IndexedDB store. */
export interface BrushPreset {
  id: string;
  name: string;
  group: string;
  tip:
    | { type: "computed"; hardness: number }
    | { type: "image"; tipId: string };
  size: number;
  spacing: number;
  roundness: number;
  angle: number;
  flow?: number;
  opacity?: number;
  shapeDynamics?: ShapeDynamics;
  transferDynamics?: TransferDynamics;
  scatterSettings?: ScatterSettings;
  dualBrush?: DualBrushSettings;
  texture?: TextureSettings;
  flipX?: boolean;
  flipY?: boolean;
  smoothing?: number;
  wetMedia?: WetMediaSettings;
  sort_order: number;
}

/** Default brush presets seeded on first DB upgrade. */
export const DEFAULT_PRESETS: BrushPreset[] = [
  {
    id: "default-hard-round",
    name: "Hard Round",
    group: "Default",
    tip: { type: "computed", hardness: 1.0 },
    size: 20,
    spacing: 0.15,
    roundness: 1.0,
    angle: 0,
    sort_order: 0,
  },
  {
    id: "default-soft-round",
    name: "Soft Round",
    group: "Default",
    tip: { type: "computed", hardness: 0.0 },
    size: 40,
    spacing: 0.15,
    roundness: 1.0,
    angle: 0,
    sort_order: 1,
  },
  // -- Oil presets --
  {
    id: "wet-oil-flat",
    name: "Oil Flat",
    group: "Oil",
    tip: { type: "computed", hardness: 0.8 },
    size: 30,
    spacing: 0.12,
    roundness: 0.4,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.9,
      paintThickness: 0.7,
      wetness: 0.6,
      mixingStrength: 0.5,
      bristleCount: 96,
      bristleSpread: 0.15,
      paintDepletionRate: 0.08,
      canvasTextureStrength: 0.3,
      mediumType: "Oil",
      viscosity: 0.8,
      bristleStiffness: 0.6,
      brushForm: 0.5,
      colorNoise: 0.15,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 10,
  },
  {
    id: "wet-oil-round",
    name: "Oil Round",
    group: "Oil",
    tip: { type: "computed", hardness: 0.6 },
    size: 24,
    spacing: 0.12,
    roundness: 1.0,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.7,
      paintThickness: 0.5,
      wetness: 0.8,
      mixingStrength: 0.7,
      bristleCount: 64,
      bristleSpread: 0.2,
      paintDepletionRate: 0.1,
      canvasTextureStrength: 0.2,
      mediumType: "Oil",
      viscosity: 0.7,
      bristleStiffness: 0.5,
      brushForm: 0.5,
      colorNoise: 0.15,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 11,
  },
  {
    id: "wet-palette-knife",
    name: "Palette Knife",
    group: "Oil",
    tip: { type: "computed", hardness: 1.0 },
    size: 40,
    spacing: 0.15,
    roundness: 0.2,
    angle: 30,
    wetMedia: {
      enabled: true,
      paintLoad: 0.1,
      paintThickness: 0.3,
      wetness: 0.9,
      mixingStrength: 0.9,
      bristleCount: 4,
      bristleSpread: 0.0,
      paintDepletionRate: 0.02,
      canvasTextureStrength: 0.1,
      mediumType: "Oil",
      viscosity: 0.3,
      bristleStiffness: 0.9,
      brushForm: 0.0,
      colorNoise: 0.0,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 12,
  },
  {
    id: "wet-oil-filbert",
    name: "Oil Filbert",
    group: "Oil",
    tip: { type: "computed", hardness: 0.7 },
    size: 28,
    spacing: 0.12,
    roundness: 0.7,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.8,
      paintThickness: 0.6,
      wetness: 0.7,
      mixingStrength: 0.6,
      bristleCount: 80,
      bristleSpread: 0.2,
      paintDepletionRate: 0.09,
      canvasTextureStrength: 0.25,
      mediumType: "Oil",
      viscosity: 0.75,
      bristleStiffness: 0.5,
      brushForm: 0.5,
      colorNoise: 0.15,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 13,
  },
  {
    id: "wet-oil-impasto",
    name: "Oil Impasto",
    group: "Oil",
    tip: { type: "computed", hardness: 0.9 },
    size: 20,
    spacing: 0.12,
    roundness: 0.8,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 1.0,
      paintThickness: 0.9,
      wetness: 0.5,
      mixingStrength: 0.3,
      bristleCount: 48,
      bristleSpread: 0.1,
      paintDepletionRate: 0.05,
      canvasTextureStrength: 0.2,
      mediumType: "Oil",
      viscosity: 0.9,
      bristleStiffness: 0.7,
      brushForm: 0.5,
      colorNoise: 0.15,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 14,
  },
  {
    id: "wet-oil-glaze",
    name: "Oil Glaze",
    group: "Oil",
    tip: { type: "computed", hardness: 0.3 },
    size: 30,
    spacing: 0.12,
    roundness: 1.0,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.2,
      paintThickness: 0.1,
      wetness: 0.4,
      mixingStrength: 0.8,
      bristleCount: 32,
      bristleSpread: 0.1,
      paintDepletionRate: 0.15,
      canvasTextureStrength: 0.15,
      mediumType: "Oil",
      viscosity: 0.6,
      bristleStiffness: 0.4,
      brushForm: 0.5,
      colorNoise: 0.15,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 15,
  },
  {
    id: "wet-dry-brush",
    name: "Dry Brush",
    group: "Oil",
    tip: { type: "computed", hardness: 0.9 },
    size: 35,
    spacing: 0.15,
    roundness: 0.6,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.3,
      paintThickness: 0.2,
      wetness: 0.15,
      mixingStrength: 0.2,
      bristleCount: 128,
      bristleSpread: 0.6,
      paintDepletionRate: 0.25,
      canvasTextureStrength: 0.5,
      mediumType: "Oil",
      viscosity: 0.8,
      bristleStiffness: 0.3,
      brushForm: 0.7,
      colorNoise: 0.2,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 16,
  },
  // -- Acrylic presets --
  {
    id: "wet-acrylic-flat",
    name: "Acrylic Flat",
    group: "Acrylic",
    tip: { type: "computed", hardness: 0.7 },
    size: 28,
    spacing: 0.12,
    roundness: 0.5,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.8,
      paintThickness: 0.4,
      wetness: 0.5,
      mixingStrength: 0.6,
      bristleCount: 80,
      bristleSpread: 0.2,
      paintDepletionRate: 0.12,
      canvasTextureStrength: 0.3,
      mediumType: "Acrylic",
      viscosity: 0.5,
      bristleStiffness: 0.5,
      brushForm: 0.5,
      colorNoise: 0.1,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 20,
  },
  {
    id: "wet-acrylic-wash",
    name: "Acrylic Wash",
    group: "Acrylic",
    tip: { type: "computed", hardness: 0.3 },
    size: 35,
    spacing: 0.12,
    roundness: 1.0,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.3,
      paintThickness: 0.1,
      wetness: 0.7,
      mixingStrength: 0.8,
      bristleCount: 48,
      bristleSpread: 0.15,
      paintDepletionRate: 0.18,
      canvasTextureStrength: 0.35,
      mediumType: "Acrylic",
      viscosity: 0.2,
      bristleStiffness: 0.3,
      brushForm: 0.5,
      colorNoise: 0.1,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 21,
  },
  {
    id: "wet-acrylic-heavy-body",
    name: "Acrylic Heavy Body",
    group: "Acrylic",
    tip: { type: "computed", hardness: 0.85 },
    size: 22,
    spacing: 0.12,
    roundness: 0.8,
    angle: 0,
    wetMedia: {
      enabled: true,
      paintLoad: 0.9,
      paintThickness: 0.7,
      wetness: 0.4,
      mixingStrength: 0.4,
      bristleCount: 64,
      bristleSpread: 0.2,
      paintDepletionRate: 0.08,
      canvasTextureStrength: 0.25,
      mediumType: "Acrylic",
      viscosity: 0.8,
      bristleStiffness: 0.6,
      brushForm: 0.5,
      colorNoise: 0.1,
    },
    shapeDynamics: WET_MEDIA_SHAPE_DYNAMICS,
    sort_order: 22,
  },
];
